version: "3.7"
services:
  my-sql:
    build: ./db
    environment:
    - MYSQL_ROOT_PASSWORD=root   
    volumes: 
      - type: volume
        source: sqlvolume
        target: /var/lib/mysql

  app:
    build: .
    ports: 
    - target: 5000
      published: 80
      protocol: tcp
    depends_on:
    - my-sql

  jenkins:
    image: jenkinsci/jenkins
    ports: 
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - app

volumes:
  sqlvolume:
